apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-web-container
          image: myprojectacr123.azurecr.io/my-web-app:v1
          ports:
            - containerPort: 80
